config/routes.rb
Rails.application.routes.draw do
  resources :animals
  resources :categories
  
  root 'animals#index'
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/problem.rb
class Problem < ApplicationRecord
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end
  
  def show
    @animal = Animal.find(params[:id])
  end
  
  def new
    @animal = Animal.new
  end
  
  def create
    @animal = Animal.new(allowed_params)
    if @animal.save
      flash[:notice] = "Successfully created animal."
      redirect_to @animal
    else
      render :new
    end
  end
  
  def edit
    @animal = Animal.find(params[:id])
  end
  
  def update
    @animal = Animal.find(params[:id])
    if @animal.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated animal."
      redirect_to @animal
    else
      render :edit
    end
  end
  
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    flash[:notice] = "Successfully destroyed animal."
    redirect_to animals_url
  end
  
  private
  
  def allowed_params
    params.require(:animal).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(allowed_params)
    if @category.save
      flash[:notice] = "Successfully created category."
      redirect_to @category
    else
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated category."
      redirect_to @category
    else
      render :edit
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Successfully destroyed category."
    redirect_to categories_url
  end
  
  private
  
  def allowed_params
    params.require(:category).permit!
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/animals/_animal.html.erb
<tr>
  <td><%=h animal.name %></td>
  <td><%=h animal.category_id %></td>
  <td><%=h animal.born_on %></td>
  <td><%=h animal.female %></td>
  <td><%= link_to "Show", animal %></td>
  <td><%= link_to "Edit", edit_animal_path(animal) %></td>
  <td><%= link_to "Destroy", animal, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>

app/views/animals/_form.html.erb
<%= semantic_form_for @animal do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :born_on, :start_year => 1900 %>
    <%= f.input :category, :include_blank => false %>
    <%= f.input :female, :as => :radio, :label => "Gender", :collection => [["Male", false], ["Female", true]] %>
  <% end %>
  
  <%= f.actions do -%>
      <%= f.action :submit, :as => :button -%>
  <% end -%>
<% end %>

app/views/animals/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @animal %> |
  <%= link_to "View All", animals_path %>
</p>

app/views/animals/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Born On</th>
    <th>Female</th>
  </tr>
  
  <%= render @animals %>
</table>

<p><%= link_to "New Animal", new_animal_path %></p>

app/views/animals/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", animals_path %></p>

app/views/animals/show.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", animals_path %></p>

app/views/categories/_category.html.erb
<tr>
  <td><%=h category.name %></td>
  <td><%=h category.description %></td>
  <td><%= link_to "Show", category %></td>
  <td><%= link_to "Edit", edit_category_path(category) %></td>
  <td><%= link_to "Destroy", category, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>

app/views/categories/_form.html.erb
<% semantic_form_for @category do |f| %>
  <%= f.inputs %>
  <%= f.actions do -%>
      <%= f.action :submit, :as => :button -%>
  <% end -%>
  
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @category %> |
  <%= link_to "View All", categories_path %>
</p>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <%= render @categories %>
</table>

<p><%= link_to "New Category", new_category_path %></p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<p><%= link_to "Back to List", categories_path %></p>

app/views/categories/show.html.erb
<h1>Category</h1>

<p>
  <strong>Name:</strong>
  <%=h @category.name %>
</p>
<p>
  <strong>Description:</strong>
  <%=h @category.description %>
</p>

<p>
  <%= link_to "Edit", edit_category_path(@category) %> |
  <%= link_to "Destroy", @category, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", categories_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <%- end -%>
            
      <%= yield %>
    </div>

  </body>
</html>